name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    env:
      DB_URI: ${{ secrets.DB_URI }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      FRONTEND: ${{ secrets.FRONTEND }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        working-directory: backend
        run: docker build -t jaivik23/quizapp-backend .
      - name: Publish image to docker hub
        run: docker push jaivik23/quizapp-backend:latest
  
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull jaivik23/quizapp-backend:latest
      - name: Delete old container
        run: docker rm -f quizapp-backend
      - name: Run docker container
        run: docker run -d -p 5000:5000 -e DB_URI=$DB_URI -e HOST=$HOST -e PORT=$PORT -e FRONTEND=$FRONTEND --name quizapp-backend jaivik23/quizapp-backend